name: Deploy to Webapp

on:
  workflow_run:
    workflows: ["CI-ACR"]   # must exactly match the OTHER workflow's name
    types:
      - completed

jobs:
  deploy:
    # This workflow only runs on workflow_run, so this reduces to "run if CI succeeded"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: static-website-docker
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ariel1devops1assigenment.azurecr.io/static-site:latest
