name: 'Deploy to Webapp'

on:
  workflow_run:
    workflows: ["CI-ACR"]  # Replace with the name of your CI workflow
    types:
      - completed  # Trigger only when the CI pipeline is completed

jobs:
  deploy:
    name: Deploy to Azure Web App
    uses: azure/webapps-deploy@v2
    with:
        app-name: my-static-site-app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ariel1devops1assigenment.azurecr.io/static-site:latest
